services:
  backend:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:80"   # <-- Cambia aquí: 3000 (host) -> 80 (nginx en el contenedor)
    restart: unless-stopped
    depends_on:
      - backend

networks:
  rafflio-network:
    driver: bridge