[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=2048"

# Configuraciones de red para SMTP
[deploy.network]
outboundConnections = ["smtp.gmail.com:587", "smtp.gmail.com:465"]

# Configuraciones de recursos
[deploy.resources]
cpu = "0.5"
memory = "512MB"

# Variables de entorno requeridas
[deploy.variables]
SMTP_USER = "info.rafflio@gmail.com"
SMTP_PASS = "yhorofchrfzdkpuk"
MERCADOPAGO_ACCESS_TOKEN = "APP_USR-4372544405719279-072718-ebb878abf215b73c1e92f6dbb02bd39d-54486551"
SUPABASE_URL = "https://lekpcbbrmbiltrrgqgmh.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxla3BjYmJybWJpbHRycmdxZ21oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NTA4NzYsImV4cCI6MjA2OTIyNjg3Nn0.A7Bpmv3PiZG_eh8AQdNGrHSZhO6MDYdLkcKRp03MVtY"
